// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD41cVSwLVRlSU4eYIZ4lasrw0SlfVKbE0',
    appId: '1:746552832931:web:1fae81dcbe5654b9582016',
    messagingSenderId: '746552832931',
    projectId: 'mindbloom-a1d34',
    authDomain: 'mindbloom-a1d34.firebaseapp.com',
    storageBucket: 'mindbloom-a1d34.firebasestorage.app',
    measurementId: 'G-RVXDCC75J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSGZeqEqcgCSKKEQKQLNecwRO0nmXyYJA',
    appId: '1:746552832931:android:a6adc10ee4ced9aa582016',
    messagingSenderId: '746552832931',
    projectId: 'mindbloom-a1d34',
    storageBucket: 'mindbloom-a1d34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfQWRxm78XqGFZFZYcTDDwobfQcxtTZ1M',
    appId: '1:746552832931:ios:1c8ed80cfc2a7c2f582016',
    messagingSenderId: '746552832931',
    projectId: 'mindbloom-a1d34',
    storageBucket: 'mindbloom-a1d34.firebasestorage.app',
    iosBundleId: 'com.example.mindbloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfQWRxm78XqGFZFZYcTDDwobfQcxtTZ1M',
    appId: '1:746552832931:ios:1c8ed80cfc2a7c2f582016',
    messagingSenderId: '746552832931',
    projectId: 'mindbloom-a1d34',
    storageBucket: 'mindbloom-a1d34.firebasestorage.app',
    iosBundleId: 'com.example.mindbloom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD41cVSwLVRlSU4eYIZ4lasrw0SlfVKbE0',
    appId: '1:746552832931:web:b20c4cd4b5dd78c4582016',
    messagingSenderId: '746552832931',
    projectId: 'mindbloom-a1d34',
    authDomain: 'mindbloom-a1d34.firebaseapp.com',
    storageBucket: 'mindbloom-a1d34.firebasestorage.app',
    measurementId: 'G-KZXCYSN96E',
  );
}
