// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVUEdE3fMMOV-6QP9KRu95XdfA6N_VIGU',
    appId: '1:770860298975:web:c4c687c599fdc9c807af6a',
    messagingSenderId: '770860298975',
    projectId: 'mindbloom-e999c',
    authDomain: 'mindbloom-e999c.firebaseapp.com',
    storageBucket: 'mindbloom-e999c.firebasestorage.app',
    measurementId: 'G-SM9S3N02SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgcA-XZcIqbmznVpKUukzqQiECxTrxC6I',
    appId: '1:770860298975:android:a422587b606b1e6307af6a',
    messagingSenderId: '770860298975',
    projectId: 'mindbloom-e999c',
    storageBucket: 'mindbloom-e999c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfQWRxm78XqGFZFZYcTDDwobfQcxtTZ1M',
    appId: '1:746552832931:ios:1c8ed80cfc2a7c2f582016',
    messagingSenderId: '746552832931',
    projectId: 'mindbloom-a1d34',
    storageBucket: 'mindbloom-a1d34.firebasestorage.app',
    androidClientId: '746552832931-r5nknftbjum72sa6alhrqu68v3fjfjr5.apps.googleusercontent.com',
    iosClientId: '746552832931-tjjave51tilphqs880uch2kgmee57qj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindbloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfQWRxm78XqGFZFZYcTDDwobfQcxtTZ1M',
    appId: '1:746552832931:ios:1c8ed80cfc2a7c2f582016',
    messagingSenderId: '746552832931',
    projectId: 'mindbloom-a1d34',
    storageBucket: 'mindbloom-a1d34.firebasestorage.app',
    androidClientId: '746552832931-r5nknftbjum72sa6alhrqu68v3fjfjr5.apps.googleusercontent.com',
    iosClientId: '746552832931-tjjave51tilphqs880uch2kgmee57qj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindbloom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVUEdE3fMMOV-6QP9KRu95XdfA6N_VIGU',
    appId: '1:770860298975:web:d37fdde82a19359b07af6a',
    messagingSenderId: '770860298975',
    projectId: 'mindbloom-e999c',
    authDomain: 'mindbloom-e999c.firebaseapp.com',
    storageBucket: 'mindbloom-e999c.firebasestorage.app',
    measurementId: 'G-8R636V9JX8',
  );

}