// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPJ86vUk7iReLxQzD952CiKXiaATg-GFg',
    appId: '1:878688910170:web:84fc6731f0389b8116d163',
    messagingSenderId: '878688910170',
    projectId: 'belfort-d347a',
    authDomain: 'belfort-d347a.firebaseapp.com',
    storageBucket: 'belfort-d347a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmsbUOQFG4-9xEzEiT7NtLGrywjDQdunM',
    appId: '1:878688910170:android:136e0cc3498003af16d163',
    messagingSenderId: '878688910170',
    projectId: 'belfort-d347a',
    storageBucket: 'belfort-d347a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfQWRxm78XqGFZFZYcTDDwobfQcxtTZ1M',
    appId: '1:746552832931:ios:1c8ed80cfc2a7c2f582016',
    messagingSenderId: '746552832931',
    projectId: 'mindbloom-a1d34',
    storageBucket: 'mindbloom-a1d34.firebasestorage.app',
    androidClientId: '746552832931-r5nknftbjum72sa6alhrqu68v3fjfjr5.apps.googleusercontent.com',
    iosClientId: '746552832931-tjjave51tilphqs880uch2kgmee57qj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindbloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfQWRxm78XqGFZFZYcTDDwobfQcxtTZ1M',
    appId: '1:746552832931:ios:1c8ed80cfc2a7c2f582016',
    messagingSenderId: '746552832931',
    projectId: 'mindbloom-a1d34',
    storageBucket: 'mindbloom-a1d34.firebasestorage.app',
    androidClientId: '746552832931-r5nknftbjum72sa6alhrqu68v3fjfjr5.apps.googleusercontent.com',
    iosClientId: '746552832931-tjjave51tilphqs880uch2kgmee57qj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindbloom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPJ86vUk7iReLxQzD952CiKXiaATg-GFg',
    appId: '1:878688910170:web:418dcb4333e5ba2716d163',
    messagingSenderId: '878688910170',
    projectId: 'belfort-d347a',
    authDomain: 'belfort-d347a.firebaseapp.com',
    storageBucket: 'belfort-d347a.firebasestorage.app',
  );

}